name: boxwallet
summary: BoxWallet is a multi-coin CLI tool, that gets your wallet/node running fast!
description: |
  BoxWallet is a single binary multi-coin CLI tool, that gets your coin-of-choice wallet/node set-up fast with just a few commands:

  boxwallet coin - allows you to choose your coin of choice, which then downloads the projects core files from their official website and installs them automatically.

  boxwallet start - starts the coin's daemon, which syncs the Blockchain.

  boxwallet dash - displays a dashboard with the coins Blockchain and wallet info.
base: core18
version: "0.40.4"

parts:
  boxwallet:
    source: https://github.com/richardltc/boxwallet.git
    plugin: go

apps:
  boxwallet:
    command: boxwallet

confinement: strict
